image: registry-docker.pamirs.com/docker:18.09
variables:
  # When using dind, it's wise to use the overlayfs driver for
  # improved performance.
  DOCKER_DRIVER: overlay2
before_script:
  - docker login -u pamirs -p wV7khLrohoGfDATmnEBazGYq registry-docker.pamirs.com
stages:
  - Dev
  - Staging
  - Production
dev:
  only:
    - dev
  stage: Dev
  script:
    - app=commonservice-api
    - env=dev
    - docker build -f Dockerfile -t $app .
    - docker tag $app registry-docker.pamirs.com/$app-$env
    - docker push registry-docker.pamirs.com/$app-$env
    - curl -X POST -F token=71af7208d6017d9dacdc2c5ce9f3fd -F ref=$app http://c.pamirs.com/api/v4/projects/105/trigger/pipeline
stagging:
  only:
    - staging
  stage: Staging
  script:
    - app=commonservice-api
    - env=sta
    - docker build -f Dockerfile -t $app .
    - docker tag $app registry-docker.pamirs.com/$app-$env
    - docker push registry-docker.pamirs.com/$app-$env
    - curl -X POST -F token=f69b04a2a3bdcef1dd339432d7e9f8 -F ref=$app http://c.pamirs.com/api/v4/projects/12/trigger/pipeline
production:
  only:
    - master
  tags:
    - prod_runners
  stage: Production
  script:
    - tag=$(date +%Y%m%d)
    - app=commonservice-api
    - env=aliyun
    - docker build -f Dockerfile -t $app .
    - docker tag $app registry-docker.pamirs.com/$app-$env:$tag
    - docker push registry-docker.pamirs.com/$app-$env:$tag
    - docker tag $app registry-docker.pamirs.com/$app-$env:latest
    - docker push registry-docker.pamirs.com/$app-$env:latest
    - curl -X POST -F token=47765d326954bcd9cb571b0bf3d92a  -F ref=$app http://c.pamirs.com/api/v4/projects/42/trigger/pipeline
    - curl -X POST -F token=9ea0fd745c9764ffa17b9508f5efed -F ref=$app http://c.pamirs.com/api/v4/projects/117/trigger/pipeline